Using u64 instead of usize to avoid overflow issues on 32-bit architectures (#354)
```
assertion failed: `(left == right)`:
./tests/data/collapse-ghcprof/results/utf8_bytes.txt:12
Diff < left / right > :
<MAIN.MAIN;Lib.你好世界 4294967295
>MAIN.MAIN;Lib.你好世界 90486357376
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failures:
    collapse_utf8_bytes

thread 'collapse_guess_dtrace_hex_addresses' (10598) panicked at tests/common/collapse.rs:34:9:
./tests/data/collapse-dtrace/results/hex-addresses.txt has more lines than output, beginning at line: 1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failures:
    collapse_guess_dtrace_hex_addresses
```